package MyPackEnterprise;
// Generated 17 ene 2022 10:25:02 by Hibernate Tools 5.5.7.Final

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int productId;
	private String name;
	private double price;

	public Products() {
	}

	public Products(int productId, String name, double price) {
		this.productId = productId;
		this.name = name;
		this.price = price;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
